Detect object properties usage inside getUsages
grafana/levitate pull request #176
Opened 2022-09-19 07:11 UTC by academo

Closes: https://github.com/grafana/levitate/issues/149

Adds detection of access to object properties to the `getUsage` API. 

This doesn't affect (yet) the is-compatible command as the compareDiff doesn't report object properties .

Examples of detection can be found in the unit tests.

2022-09-19 07:12 UTC, academo commented on fixtures/usage/object-properties/package.json
> +{
This package.json is required for the fixtures we use for testing and development.

Typescript can only report the correct parent symbols if they are declared and loaded as modules from node_modules.

2022-09-19 07:14 UTC, academo commented on src/bin.ts
> +if (process.env.DEBUG) {
While working with the nodejs I noticed the debugger gets into a deadlock because of how yargs handle the exit events that I can't overwrite. 

This is a solution to force the debut to disconnect when the process emits the exit event.

Notice that usually is useful to have the debugger still connected when the script finishes but in this specific case the debugger is not usable and the only thing you can do with it is to close it or refresh it.

2022-09-20 07:57 UTC, leventebalogh requested changes
Nice new feature! I also really like that we have tests covering it. 👏

2022-09-20 07:57 UTC, leventebalogh commented on src/bin.ts
> +if (process.env.DEBUG) {
**Suggestion:** I think we can get rid of the condition here (`if (process.env.DEBUG) { ... }`) as it is already checked in the underlying function.

2022-09-20 07:57 UTC, leventebalogh commented on src/utils/typescript.ts
> +  const identifiers: ts.PropertyAccessExpression[] = [];
**Suggestion:** I would rather use the name `expressions` for this variable here (for consistency)
```suggestion
  const expresions: ts.PropertyAccessExpression[] = [];
```

2022-09-20 07:57 UTC, leventebalogh commented on src/utils/typescript.ts
> +  });
**Suggestion:** I would either rename `COMPILER_OPTIONS` to `COMPILER_OPTIONS_DEFAULT`, or `compilerOptions` to `compilerOptionsOverrides`.

2022-09-20 07:57 UTC, leventebalogh commented on fixtures/usage/object-properties/use-theme.tsx
> +export default MyComponent;
**Question:** are we using these fixtures anywhere?

2022-09-20 07:58 UTC, academo commented on src/bin.ts
> +}
Ahh! that was because of a different approach I had before. I can put it back now that I did this way.

2022-09-20 07:59 UTC, academo commented on src/bin.ts
> +if (process.env.DEBUG) {
Maybe. But I want to make emphasis in the code that this is a debug-only function.

2022-09-20 08:01 UTC, academo commented on src/usage/usage.ts
> +  const checker = project.getTypeChecker();
For now. But I am sure we will need more than the checker later on with modifications. Also it makes no difference.

2022-09-20 08:02 UTC, academo commented on fixtures/usage/object-properties/use-theme.tsx
> +export default MyComponent;
Yes. When I develop levitate I use them extensively.

2022-09-20 08:03 UTC, academo commented on src/usage/test-utils.ts
> +  testingModuleName = 'testing-module',
I don't really think this makes a difference.

2022-09-20 08:05 UTC, academo commented on src/usage/usage.test.ts
> +      });
A valid concern but I don't think it hides anything. The name of the function and parameters clearly indicate what it does and the way is used makes it clearer once you see the code.

I don't see any advantage of having more repetitive code in these tests.

2022-09-20 08:14 UTC, leventebalogh commented on src/bin.ts
> +if (process.env.DEBUG) {
Hehe, let's add the condition one more time then, so it's easier to understand.

Jokes aside, we can also leave the condition in this file only and remove it from the function. Or keep it in the function and change its name so it reveals that it should be used for debug purposes. It's not crucial from the _functional_ perspective, but the current implementation is redundant and redundancies make the code harder to reason about later. Maybe a line today, but a year later a thousand more little redundancies like this take us to a codebase which is harder to read and understand.

2022-09-20 09:01 UTC, mckn commented on src/usage/usage.test.ts
> +      });
I agree with Levi here. I think the tests serve two purposes.

1. To verify that the functionality works as expected now and in the future when we introducing changes.
2. Documentation so when any of us (or a new person) re-visit the code base, they can read the tests to understand the functionality and how it is supposed to be used.

I had a quick look at the code since we are abstracting away the setup in multiple files you need to navigate 3 different files to understand how it is setup. With that said I think we can make some small improvements to make the tests more readable. 

Also, a nit from my side. The way we currently have formatted the template strings makes it really hard to read. So changing that would be a quick win!

2022-09-20 09:26 UTC, jackw commented on src/usage/test-utils.ts
> +  testingModuleName = 'testing-module',
Maybe it's just me but I try to name arguments the same as a functions parameters where possible (which I think is what Levi is suggesting here). I certainly find it easier to skim read code as things are passed around and I have to go from file to file.

2022-09-21 07:25 UTC, academo commented on src/usage/usage.test.ts
> +      });
@mckn can you elaborate on the template strings formatting? What makes it difficult to read?

The testing code will become very repetitive if we split it. I don't really think much or any is achieved by changing it but if the consensus is I should I'll do the change.

2022-09-21 07:43 UTC, academo commented on src/usage/usage.test.ts
> +      });
I pushed the change to remove some responsability from the test utility back to the test itself.

2022-09-21 07:46 UTC, academo commented on src/usage/usage.ts
> +  const checker = project.getTypeChecker();
To further expand my previous comment:

While working on other parts of leviate I identified that the program and checker are far more important to have at hand than only the typescript nodes or symbols and you can't reliably fetch the program from the symbols.

In this specific case we only need the checker but I suspect, as we have to expand the functionality to cover more cases like destructuring, import aliases and other edge cases, we'll need more of the utilities and properties included in both the program and the checker.

In other words I learnt that it is better to have the program at hand at any moment you are doing operations over nodes and symbols.

2022-09-21 07:48 UTC, academo commented on src/usage/test-utils.ts
> +  testingModuleName = 'testing-module',
I renamed them to use the word "package" as suggested.

2022-09-22 11:14 UTC, leventebalogh commented on src/usage/usage.test.ts
> +      const use = usages.get(mainFile);
Would it make sense to extract these lines to a utility function in this file to remove the repetition?
```javascript
const getUsedNamesForFile = (usages: Map<ts.SourceFile, Record<string, IdentifierWithCounter>>, fileName: string) => {
   const file = Array.from(usages.keys()).find((f) => f.fileName === filename);

    return usages.get(file);
}

// ...

const allUsages = getPackageUsage(projectProgram, testingModuleExports, testingPackageName);
const usedNames = getUsedNamesForFile(allUsages, projectFile);

expect(usedNames).toEqual(['Bar']);
```

2022-09-22 11:16 UTC, leventebalogh commented on src/bin.ts
> +if (process.env.DEBUG) {
Looking at it from another angle, what is the reason for having it in both places?

2022-09-22 11:19 UTC, leventebalogh commented on src/usage/usage.test.ts
> +      });
> The testing code will become very repetitive if we split it. I don't really think much or any is achieved by changing it but if the consensus is I should I'll do the change.

I am sorry if I was not clear on this, I didn't mean that we should make the code more repetitive, more like that if we use the `getPackageUsage()` function explicitly in the tests then they are easier to be used as a documentation as well. What do you think about https://github.com/grafana/levitate/pull/176#discussion_r977519815 to reduce some of the repetition?

2022-09-22 12:33 UTC, mckn commented on src/usage/usage.test.ts
> +      });
> @mckn can you elaborate on the template strings formatting? What makes it difficult to read?
> 
> The testing code will become very repetitive if we split it. I don't really think much or any is achieved by changing it but if the consensus is I should I'll do the change.

As I wrote in PM. It is the code snippets within e.g. `projectSrc` which you already have fixed 🙌🏻

2022-09-22 13:14 UTC, leventebalogh approved these changes

2022-09-22 13:55 UTC, merged